### ISSUE TITLE
Channels are not considers for private repositories

### ISSUE THREAD

**Issue by pradal** [openalea/github-action-conda-build#1]
ANACONDA_CHANNELS is defined in github as an organisation variable.
However, it is only set if the rpository is public.

Add the channels as an option of the action to overpass this limitation

**Comment by thomasarsouze** [comment]
Do we really want to publish conda packages on our channel from private repositories ?

**Comment by pradal** [comment]
Perhaps not, but we want to use Continuous integration, anywway.
Because all the private packages will become public later on.

**Comment by thomasarsouze** [comment]
Ok, but then you can still use the continuous integration for building / testing, right ?
`ANACONDA_CHANNELS` is only used for publication on conda, and will then be used once the repo becomes public.

**Comment by pradal** [comment]
No it is also use to find conda deps

**Comment by pradal** [comment]
openalea.plantgl for instance

**Comment by thomasarsouze** [comment]
OK, I see the problem... sorry it's been a while since I didn't touched this code.

Instead of modifying the code, I think it's best to override the default `ANACONDA_CHANNELS` as default value for input.conda-channels and set it hard-coded `openalea3`.

This has no other implication as the package won't be published.

What do you think ?

**Comment by pradal** [comment]
Just to be clear, I just copy the old code by setting in hard openalea3 and condda-forge.
The only thing I need is a deps on openalea3.
If not, I can not build neither insttall the package that will depends on other packages in openalea3

**Comment by thomasarsouze** [comment]
I think you want something like this:
```
name: Building Package

on:
  push:
    branches: 
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches: 
      - '**'


jobs:
  build:
    uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@main
    with:
         conda-channels: openalea3
    secrets: 
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
```
