### ISSUE TITLE
How to set the conda directory location

### ISSUE THREAD

**Issue by pradal** [openalea/github-action-conda-build#2]
I need to set the conda directory location in a complex repository:
[openalea-component](https://github.com/openalea/openalea-components)

Various packages are tested independently. So I need to inform each one to build pylab, pkgbuilder and the like.
How to do so?

Something like 

```
with:
    conda : pylab/conda
```

**Comment by pradal** [comment]
Could I set an order? For instance I need to build stdlib before others...

**Comment by thomasarsouze** [comment]
I guess you can define your workflow that'll wait for the end of one job to start another one. Something like:
```
jobs:
  build:
    steps:
      - name: build-stdlib
         uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@main
           with:
             conda: stdlib/conda
           secrets: 
             anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
      - name: build-pylab
         uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@main
           with:
             conda: pylab/conda
           secrets: 
             anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
```
